DonutQueen/Controllers/AdminController.cs
using DonutQueen.Data;
using DonutQueen.Data.Repositories;
using DonutQueen.Models;
using DonutQueen.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DonutQueen.Controllers
{
    public class AdminController : Controller
    {
        //private readonly DonutQueenContext _context;
        private readonly IDonutRepository _donutRepository;
       

        public AdminController(IDonutRepository donutRepository)
        {
            _donutRepository = donutRepository;
        }

       

        [HttpGet(nameof(GetDonutById))]
        public async Task<string> GetDonutById(int donutID)
        {
            var result = await _donutRepository.GetDonutById(donutID);
            return result;
        }

        public IActionResult Donuts()
        {
            DonutOverviewViewModel vm = new DonutOverviewViewModel()
            {
                Donuts = _donutRepository.GetDonuts()
            };

            return View(vm);
        }



        public async Task<IActionResult> DonutDetails(int id)
        {
            Donut donut = await _donutRepository.GetDonut(id);
            if (donut != null)
            {
                DonutDetailsViewModel vm = new DonutDetailsViewModel()
                {
                    DonutId = id,
                    Naam = donut.Naam,
                    Topping = donut.Topping,
                    Glazuur = donut.Glazuur,
                    Vulling = donut.Vulling,
                    Omschrijving = donut.Omschrijving,
                    IsVegan = donut.IsVegan,
                    Afbeelding = donut.Afbeelding,
                    Prijs = donut.Prijs
                };

                return View(vm);
            }
            else
            {
                DonutOverviewViewModel vm = new DonutOverviewViewModel()
                {
                    Donuts = _donutRepository.GetDonuts().ToList()
                };
                return View("Index", vm);
            }
        }

        [HttpGet]
        public IActionResult CreateDonut()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDonut(CreateDonutViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                /* _context.Add(new Donut()
                {
                    Naam = viewModel.Naam,
                    Topping = viewModel.Topping,
                    Glazuur = viewModel.Glazuur,
                    Vulling = viewModel.Vulling,
                    Omschrijving = viewModel.Omschrijving,
                    IsVegan = viewModel.IsVegan,
                    Afbeelding = viewModel.Afbeelding,
                    Prijs = viewModel.Prijs
                });*/

                await _donutRepository.AddDonut(new Donut()
                {
                    Naam = viewModel.Naam,
                    Topping = viewModel.Topping,
                    Glazuur = viewModel.Glazuur,
                    Vulling = viewModel.Vulling,
                    Omschrijving = viewModel.Omschrijving,
                    IsVegan = viewModel.IsVegan,
                    Afbeelding = viewModel.Afbeelding,
                    Prijs = viewModel.Prijs
                });

                return RedirectToAction(nameof(Donuts));
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditDonut(int id)
        {
           /* if (id == null)
                return NotFound();*/

            Donut donut = await _donutRepository.GetDonut(id);

            if (donut == null)
                return NotFound();

            EditDonutViewModel vm = new EditDonutViewModel()
            {
                DonutId = donut.DonutId,
                Naam = donut.Naam,
                Topping = donut.Topping,
                Glazuur = donut.Glazuur,
                Vulling = donut.Vulling,
                Omschrijving = donut.Omschrijving,
                IsVegan = donut.IsVegan,
                Afbeelding = donut.Afbeelding,
                Prijs = donut.Prijs
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditDonut(int id, EditDonutViewModel viewModel)
        {
            if (id != viewModel.DonutId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    Donut donut = new Donut()
                    {
                        DonutId = viewModel.DonutId,
                        Naam = viewModel.Naam,
                        Topping = viewModel.Topping,
                        Glazuur = viewModel.Glazuur,
                        Vulling = viewModel.Vulling,
                        Omschrijving = viewModel.Omschrijving,
                        IsVegan = viewModel.IsVegan,
                        Afbeelding = viewModel.Afbeelding,
                        Prijs = viewModel.Prijs
                    };
                    
                   await _donutRepository.UpdateDonut(donut);

                }
                catch (DbUpdateConcurrencyException e)
                {
                    if ( await _donutRepository.GetDonut(id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Donuts));
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteDonut(int id)
        {
            // Donut donut = _context.Donuts.Where(d => d.DonutId == id).FirstOrDefault();

            Donut donut = await _donutRepository.GetDonut(id);

            if (donut != null)
            {
                DeleteDonutViewModel vm = new DeleteDonutViewModel()
                {
                    DonutId = id,
                    Naam = donut.Naam,
                    Topping = donut.Topping,
                    Glazuur = donut.Glazuur,
                    Vulling = donut.Vulling,
                    Omschrijving = donut.Omschrijving,
                    IsVegan = donut.IsVegan,
                    Afbeelding = donut.Afbeelding,
                    Prijs = donut.Prijs
                };

                return View(vm);
            }
            else
            {
                DonutOverviewViewModel vm = new DonutOverviewViewModel()
                {
                    Donuts = _donutRepository.GetDonuts()
                };
                return View("Index", vm);
            }
        }

        [HttpPost, ActionName("DeleteDonut")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteDonutConfirm(int id)
        {
            await _donutRepository.DeleteDonut(id);
            //await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Donuts));
        }


        public IActionResult Winkels()
        {
            WinkelOverviewViewModel vm = new WinkelOverviewViewModel()
            {
                Winkels = _context.Winkels.ToList()
            };
            
            return View(vm);
        }

        public IActionResult Gebruikers()
        {
            return View();
        }

        public IActionResult Orders()
        {
            return View();
        }
    }
}

DonutQueen/Controllers/ShopController.cs
using DonutQueen.Data;
using DonutQueen.Models;
using DonutQueen.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace DonutQueen.Controllers
{
    public class ShopController : Controller
    {

        private readonly DonutQueenContext _context;

        public ShopController(DonutQueenContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ShopViewModel vm = new ShopViewModel()
            {
                Donuts = _context.Donuts.ToList()
            };

            return View(vm);
        }

        public IActionResult Details(int id)
        {
            Donut donut = _context.Donuts.Where(d => d.DonutId == id).FirstOrDefault();

            ShopDetailsViewModel vm = new ShopDetailsViewModel()
            {
                Naam = donut.Naam,
                Topping = donut.Topping,
                Glazuur = donut.Glazuur,
                Vulling = donut.Vulling,
                Omschrijving = donut.Omschrijving,
                IsVegan = donut.IsVegan,
                Afbeelding = donut.Afbeelding,
                Prijs = donut.Prijs
            };

            return View(vm);
        }
    }
}

DonutQueen/Controllers/WinkelController.cs
using DonutQueen.Data;
using DonutQueen.Models;
using DonutQueen.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace DonutQueen.Controllers
{
    public class WinkelController : Controller
    {

        private readonly DonutQueenContext _context;

        public WinkelController(DonutQueenContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            WinkelsViewModel vm = new WinkelsViewModel()
            {
                Winkels = _context.Winkels.ToList()
            };

            return View(vm);
        }
    }
}

DonutQueen/Views/Shared/_DonutQueenLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DonutQueen - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/donutqueen.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-custom bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo_dq.png" width="45" height="45" alt="Logo Donut Queen">
                    Donut Queen
                </a>
                <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarCustom">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarCustom">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Winkel" asp-action="Index">Onze winkels</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Admin </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Admin" asp-action="Donuts">Donuts</a>
                                <a class="dropdown-item" asp-controller="Admin" asp-action="Winkels">Winkels</a>
                                <a class="dropdown-item" asp-controller="Admin" asp-action="Gebruikers">Gebruikers</a>
                                <a class="dropdown-item" asp-controller="Admin" asp-action="Orders">Orders</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DonutQueen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>